// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaj0AceYFJ6M6kBWApXulxpVpvXOgKBUk',
    appId: '1:70415903447:web:ca0e2763399947bcb3de92',
    messagingSenderId: '70415903447',
    projectId: 'project-manager-flutter-eb7e8',
    authDomain: 'project-manager-flutter-eb7e8.firebaseapp.com',
    storageBucket: 'project-manager-flutter-eb7e8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJS96bsqHHFY_DQj2OsL_yd2aW18xfxC8',
    appId: '1:70415903447:android:c5aaff04b5ac06c5b3de92',
    messagingSenderId: '70415903447',
    projectId: 'project-manager-flutter-eb7e8',
    storageBucket: 'project-manager-flutter-eb7e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe1YSY985GVMG6MaSMZFGmLgbfBAW7i-g',
    appId: '1:70415903447:ios:2967c8d9da3fc120b3de92',
    messagingSenderId: '70415903447',
    projectId: 'project-manager-flutter-eb7e8',
    storageBucket: 'project-manager-flutter-eb7e8.firebasestorage.app',
    iosBundleId: 'com.example.iosMobileDevelopment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe1YSY985GVMG6MaSMZFGmLgbfBAW7i-g',
    appId: '1:70415903447:ios:2967c8d9da3fc120b3de92',
    messagingSenderId: '70415903447',
    projectId: 'project-manager-flutter-eb7e8',
    storageBucket: 'project-manager-flutter-eb7e8.firebasestorage.app',
    iosBundleId: 'com.example.iosMobileDevelopment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaj0AceYFJ6M6kBWApXulxpVpvXOgKBUk',
    appId: '1:70415903447:web:bcf4983bb1f56b06b3de92',
    messagingSenderId: '70415903447',
    projectId: 'project-manager-flutter-eb7e8',
    authDomain: 'project-manager-flutter-eb7e8.firebaseapp.com',
    storageBucket: 'project-manager-flutter-eb7e8.firebasestorage.app',
  );

}